% restrict results to principal sector plus guard
% $Id$
function x = cull(v, guard),
  if (nargin < 2),
    guard = 0;
  end
  x = v(:,2:4) ./ repmat(v(:,1)+(v(:,1)==0)*1.e-10,1,3);
  m = x(:,1) - (sqrt(2) -1) <= guard & ...
      x(:,2) - (sqrt(2) -1) <= guard & ...
      x(:,3) - (sqrt(2) -1) <= guard & ...
      x(:,1) + x(:,2) + x(:,3) - 1 <= sqrt(3)*guard & ...
      x(:,1) >= -guard & ...
      x(:,2) >= -guard & ...
      x(:,3) >= -guard & ...
      x(:,1) - x(:,2) >= -sqrt(2)*guard & ...
      x(:,2) - x(:,3) >= -sqrt(2)*guard;
  x = v(m,:);
end

